/* eslint-disable global-require */
module.exports = {
  configs: {
    base: require('./configs/base'),
    nuxt: require('./configs/nuxt'),
    'nuxt-typescript': require('./configs/nuxt-typescript'),
    tailwindcss: require('./configs/tailwindcss'),
    typescript: require('./configs/typescript'),
    'vue-typescript': require('./configs/vue-typescript'),
    vue: require('./configs/vue'),
  },
  rules: {
    'newline-before-first-type-only-import': require('./rules/newline-before-first-type-only-import'),
    'pinia-no-function-expressions': require('./rules/pinia-no-function-expressions'),
    'pinia-setup-newlines-between-groups': require('./rules/pinia-setup-newlines-between-groups'),
    'pinia-setup-newlines-inside-groups': require('./rules/pinia-setup-newlines-inside-groups'),
    'pinia-setup-order': require('./rules/pinia-setup-order'),
    'pinia-setup-return': require('./rules/pinia-setup-return'),
    'pinia-style': require('./rules/pinia-style'),
    'vue-block-attributes-order': require('./rules/vue-block-attributes-order'),
    'vue-computed-property-return-type': require('./rules/vue-computed-property-return-type'),
    'vue-dom-class-no-capital-letters': require('./rules/vue-dom-class-no-capital-letters'),
    'vue-dom-id-no-capital-letters': require('./rules/vue-dom-id-no-capital-letters'),
    'vue-method-return-type': require('./rules/vue-method-return-type'),
    'vue-no-compiler-macro-imports': require('./rules/vue-no-compiler-macro-imports'),
    'vue-no-function-expressions': require('./rules/vue-no-function-expressions'),
    'vue-no-multiple-template-root': require('./rules/vue-no-multiple-template-root'),
    'vue-script-setup-newlines-inside-groups': require('./rules/vue-script-setup-newlines-inside-groups'),
    'vue-script-setup-newlines-between-groups': require('./rules/vue-script-setup-newlines-between-groups'),
    'vue-script-setup-order': require('./rules/vue-script-setup-order'),
    'vue-v-on-handler-style': require('./rules/vue-v-on-handler-style'),
  },
};
