module.exports = {
  parserOptions: {
    ecmaVersion: 2020,
    sourceType: 'module',
  },

  plugins: [
    'vue',
    '@programic',
  ],

  extends: [
    require.resolve('./base'),
    'plugin:vue/vue3-recommended',
  ],

  overrides: [
    {
      files: ['*.vue'],
      rules: { indent: 'off' },
    },
  ],

  rules: {
    'no-use-before-define': ['error', {
      allowNamedExports: false,
      functions: false,
      variables: true,
      classes: true,
    }],
    '@programic/pinia-style': 'error',
    '@programic/pinia-setup-order': 'error',
    '@programic/pinia-setup-return': 'error',
    '@programic/pinia-no-function-expressions': 'error',
    '@programic/vue-block-attributes-order': 'error',
    '@programic/vue-dom-id-no-capital-letters': 'error',
    '@programic/vue-dom-class-no-capital-letters': 'error',
    '@programic/vue-no-compiler-macro-imports': 'error',
    '@programic/vue-no-multiple-template-root': 'error',
    '@programic/vue-no-function-expressions': 'error',
    '@programic/vue-script-setup-newlines-inside-groups': 'error',
    '@programic/vue-script-setup-newlines-between-groups': 'error',
    '@programic/vue-script-setup-order': 'error',
    'unicorn/prevent-abbreviations': ['error', {
      checkShorthandProperties: true,
      checkProperties: true,
      ignore: [
        /^src$/i,
        // Vue specific ignores
        /attrs|params|prop|props|ref|refs/i,
      ],
    }],
    'vue/script-indent': ['error', 2, {
      baseIndent: 1,
      switchCase: 1,
    }],
    'vue/no-v-html': 'off',
    'vue/html-self-closing': ['error', {
      html: {
        void: 'never',
        normal: 'never',
        component: 'always',
      },
      svg: 'never',
      math: 'never',
    }],
    'vue/attributes-order': ['error', {
      order: [
        'DEFINITION',
        'LIST_RENDERING',
        'CONDITIONALS',
        'RENDER_MODIFIERS',
        'GLOBAL',
        'UNIQUE',
        'SLOT',
        'TWO_WAY_BINDING',
        'OTHER_DIRECTIVES',
        'ATTR_DYNAMIC',
        'ATTR_STATIC',
        'ATTR_SHORTHAND_BOOL',
        'EVENTS',
        'CONTENT',
      ],
    }],
    'vue/component-tags-order': ['error', {
      order: ['script', 'template', 'style'],
    }],
    'vue/no-lone-template': 'error',
    'vue/no-multiple-slot-args': 'error',
    'vue/order-in-components': 'error',
    'vue/this-in-template': 'error',
    'vue/attribute-hyphenation': 'error',
    'vue/component-definition-name-casing': 'error',
    'vue/first-attribute-linebreak': 'error',
    'vue/html-closing-bracket-newline': 'error',
    'vue/html-closing-bracket-spacing': 'error',
    'vue/html-end-tags': 'error',
    'vue/html-indent': 'error',
    'vue/html-quotes': 'error',
    'vue/max-attributes-per-line': 'error',
    'vue/multiline-html-element-content-newline': 'error',
    'vue/mustache-interpolation-spacing': 'error',
    'vue/no-multi-spaces': 'error',
    'vue/no-spaces-around-equal-signs-in-attribute': 'error',
    'vue/no-template-shadow': 'error',
    'vue/one-component-per-file': 'error',
    'vue/prop-name-casing': 'error',
    'vue/require-default-prop': 'error',
    'vue/require-explicit-emits': 'error',
    'vue/require-prop-types': 'error',
    'vue/singleline-html-element-content-newline': 'error',
    'vue/v-bind-style': 'error',
    'vue/v-on-style': 'error',
    'vue/v-slot-style': 'error',
    'vue/component-api-style': ['error', ['script-setup']],
    'vue/component-name-in-template-casing': 'error',
    'vue/component-options-name-casing': 'error',
    'vue/custom-event-name-casing': 'error',
    'vue/define-emits-declaration': ['error', 'runtime'],
    'vue/define-macros-order': 'error',
    'vue/define-props-declaration': ['error', 'runtime'],
    'vue/html-button-has-type': 'error',
    'vue/html-comment-content-newline': 'error',
    'vue/html-comment-content-spacing': 'error',
    'vue/html-comment-indent': 'error',
    'vue/new-line-between-multi-line-property': 'error',
    'vue/next-tick-style': 'error',
    'vue/no-duplicate-attr-inheritance': 'error',
    'vue/no-empty-component-block': 'error',
    'vue/no-multiple-objects-in-class': 'error',
    'vue/no-ref-object-destructure': 'error',
    'vue/no-required-prop-with-default': 'error',
    'vue/no-this-in-before-route-enter': 'error',
    'vue/no-undef-components': ['error', {
      ignorePatterns: [
        '^Router(View|Link)$',
        '^Nuxt(ClientFallback|Page|Layout|Link|LoadingIndicator|ErrorBoundary|Welcome)$',
        '^ClientOnly$',
      ],
    }],
    'vue/no-unused-refs': 'error',
    'vue/no-v-text': 'error',
    'vue/padding-line-between-blocks': 'error',
    'vue/padding-line-between-tags': 'error',
    'vue/prefer-separate-static-class': 'error',
    'vue/v-on-handler-style': 'off',
    '@programic/vue-v-on-handler-style': ['error', ['method', 'inline-function'], {
      allowAnyInlineFunction: true,
    }],
    'vue/no-useless-mustaches': ['error', {
      ignoreStringEscape: true,
    }],
    'vue/no-useless-v-bind': ['error', {
      ignoreStringEscape: true,
    }],
    'vue/no-unused-properties': ['error', {
      deepData: true,
      groups: [
        'props',
        'data',
        'computed',
        'methods',
        'setup',
      ],
    }],
    'vue/padding-lines-in-component-definition': ['error', {
      groupSingleLineProperties: false,
      betweenOptions: 'always',
      withinOption: {
        components: 'never',
        mixins: 'never',
        props: {
          betweenItems: 'always',
          withinEach: 'never',
        },
        emits: 'never',
        data: 'never',
        computed: {
          betweenItems: 'always',
          withinEach: 'never',
        },
        watch: {
          betweenItems: 'always',
          withinEach: 'never',
        },
        methods: {
          betweenItems: 'always',
          withinEach: 'never',
        },
      },
    }],
    'vue/arrow-spacing': 'error',
    'vue/array-bracket-spacing': ['error', 'never'],
    'vue/comma-dangle': ['error', 'always-multiline'],
    'vue/object-curly-spacing': ['error', 'always'],
    'vue/object-shorthand': ['error', 'always', {
      ignoreConstructors: false,
      avoidQuotes: true,
    }],
    'vue/quote-props': ['error', 'as-needed', {
      keywords: false,
      unnecessary: true,
      numbers: false,
    }],
    'vue/multi-word-component-names': 'off',
    'vue/dot-location': ['error', 'property'],
    'vue/template-curly-spacing': 'error',
    'vue/func-call-spacing': 'error',
    'vue/no-useless-concat': 'error',
    'vue/no-sparse-arrays': 'error',
    'vue/prefer-template': 'error',
    'vue/space-in-parens': 'error',
    'vue/dot-notation': 'error',
    'vue/key-spacing': 'error',
    'vue/eqeqeq': 'error',
  },
};
